GET http://localhost:8000/categoria

###
GET http://localhost:8000/categoria/1

###
DELETE http://localhost:8000/categoria/2

###
GET http://localhost:8000/categoria/2

###
GET http://localhost:8000/categoria?title=Java
###
GET http://localhost:8000/categoria?content=jdbc
###
GET http://localhost:8000/categoria?title=Java&content=jdbc

###
GET http://localhost:8000/objeto

###
GET http://localhost:8000/objeto?multitle=Java,PHP

###
GET http://localhost:8000/objeto?search=java

###
GET http://localhost:8000/objeto?multisearch=java,PHP
