GET http://localhost:8000/objeto

###
GET http://localhost:8000/objeto/2365108b-7ed3-4ea2-a931-f46769e30417

###
DELETE http://localhost:8000/objeto/2

###
GET http://localhost:8000/objeto/2

###
GET http://localhost:8000/objeto?title=Java
###
GET http://localhost:8000/objeto?content=jdbc
###
GET http://localhost:8000/objeto?title=Java&content=jdbc

###
GET http://localhost:8000/objeto

###
GET http://localhost:8000/objeto?multitle=Java,PHP

###
GET http://localhost:8000/objeto?search=java

###
GET http://localhost:8000/objeto?multisearch=java,PHP

