POST http://127.0.0.1:8000/usuarios
Content-Type: application/json 

{
        "id": 4,
        "nombre": "Flavio",
        "apellido": "Profe",
        "mail": "Flavio@ingsis.com",
        "contrasenia": ""
    }

###
PUT http://127.0.0.1:8000/usuarios
Content-Type: application/json

{
        "id": 2,
        "nombre": "Flavio",
        "apellido": "Profe",
        "mail": "Flavio@ingsis.com",
        "contrasenia": ""
    }
