POST http://127.0.0.1:8000/objeto
Content-Type: application/json 

{
  "title" : "primer post",
  "content" : "mucho bla bla bla"
}

###
PUT http://127.0.0.1:8000/objeto/3dcccfb3-bb04-4209-80a1-1964b88f159b
Content-Type: application/json

{
  "id": "3dcccfb3-bb04-4209-80a1-1964b88f159b",
  "title" : "segund post",
  "content" : "mucho bla bla bla"
}
